#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile databricks-dlt.in
#
cachetools==5.5.2
    # via google-auth
certifi==2025.4.26
    # via requests
charset-normalizer==3.4.2
    # via requests
databricks-connect==16.3.2
    # via databricks-dlt
databricks-dlt==0.3.0
    # via -r databricks-dlt.in
databricks-sdk==0.52.0
    # via databricks-connect
google-auth==2.40.0
    # via databricks-sdk
googleapis-common-protos==1.70.0
    # via
    #   databricks-connect
    #   grpcio-status
grpcio==1.71.0
    # via
    #   databricks-connect
    #   grpcio-status
grpcio-status==1.71.0
    # via databricks-connect
idna==3.10
    # via requests
numpy==1.26.4
    # via
    #   databricks-connect
    #   pandas
packaging==25.0
    # via databricks-connect
pandas==2.2.3
    # via databricks-connect
protobuf==5.29.4
    # via
    #   googleapis-common-protos
    #   grpcio-status
py4j==0.10.9.7
    # via databricks-connect
pyarrow==20.0.0
    # via databricks-connect
pyasn1==0.6.1
    # via
    #   pyasn1-modules
    #   rsa
pyasn1-modules==0.4.2
    # via google-auth
python-dateutil==2.9.0.post0
    # via pandas
pytz==2025.2
    # via pandas
requests==2.32.3
    # via databricks-sdk
rsa==4.9.1
    # via google-auth
six==1.17.0
    # via
    #   databricks-connect
    #   python-dateutil
tzdata==2025.2
    # via pandas
urllib3==2.4.0
    # via requests

# The following packages are considered to be unsafe in a requirements file:
# setuptools
