{
  "libname": "sagemaker-inference",
  "libvers": "1.10.1",
  "infile": "data/pip/sagemaker-inference.txt",
  "dependencies": {
    "boto3": "1.38.10",
    "botocore": "1.38.10",
    "jmespath": "1.0.1",
    "numpy": "2.2.5",
    "psutil": "7.0.0",
    "python-dateutil": "2.9.0.post0",
    "retrying": "1.3.4",
    "s3transfer": "0.12.0",
    "scipy": "1.15.2",
    "six": "1.17.0",
    "urllib3": "2.4.0"
  }
}